# Example: `.github/workflows/release-pr.yml`

---
name: Create PR on New Release

on:
  release:
    types: [published]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Make your changes here (e.g., update files, run scripts, etc.)

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'Update development files for new release ${{ github.event.release.tag_name }}'
          branch: 'development'
          title: 'chore: Update development for new release ${{ github.event.release.tag_name }}'
          body: |
            This pull request updates development files following the new release: ${{ github.event.release.tag_name }}.
          labels: |
            automated pr
          reviewers: |
            visze
